Repository SuperZooper3/reci, pull requests merged in 2025-06, with the labels that each got.

#33 30 update init script to include new tables
  backend/sql/getAccountNames.sql
  backend/sql/getUserNames.sql
  backend/sql/init.sql
  backend/sql/seed.sql
  backend/src/controllers/accountController.ts
  backend/src/db.ts
  backend/src/index.ts
  frontend/src/App.tsx
Labels: review-needed

#42 Add SQL query to get User reviews
  backend/sql/getAccountReviews.sql
Labels: review-needed

#43 feat: add getAccountFollowers.sql
  backend/sql/getAccountFollowers.sql
  backend/sql/init.sql
Labels: review-needed

#49 feat: add getAccountRecipes.sql
  backend/sql/getAccountRecipes.sql
  backend/sql/getAccountReviews.sql
Labels: review-needed

#72 feat: add more seeding data
  backend/sql/init.sql
  backend/sql/seed.sql
Labels: review-needed

#92 feat: Added recipes endpoint, shadcn input, and markdown support
  backend/sql/getAccountRecipes.sql
  backend/sql/seed.sql
  backend/src/controllers/recipeController.ts
  backend/src/index.ts
  backend/src/models/recipeModel.ts
  backend/src/routes/recipeRoutes.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/ui/input.tsx
Labels: review-needed

#93 feat: add getAccount
  backend/sql/getAccount.sql
  backend/sql/getAccountCreatedAtAndUsername.sql
  backend/src/controllers/accountController.ts
  backend/src/models/accountModel.ts
  backend/src/routes/accountRoutes.ts
Labels: review-needed

#91 Add account deletion endpoint
  backend/src/controllers/accountController.ts
  backend/src/models/accountModel.ts
  backend/src/routes/accountRoutes.ts
Labels: review-needed

#98 Add new recipes post endpoint
  backend/src/controllers/recipeController.ts
  backend/src/models/recipeModel.ts
  backend/src/routes/recipeRoutes.ts
Labels: review-needed

#97 Get recipe by id
  backend/sql/getRecipe.sql
  backend/src/controllers/recipeController.ts
  backend/src/models/recipeModel.ts
  backend/src/routes/recipeRoutes.ts
  frontend/src/App.tsx
Labels: review-needed

#108 feat: added recipe types
  backend/src/models/recipeModel.ts
  shared-types/index.ts
  shared-types/recipeTypes.ts
Labels: review-needed

#109 Add review endpoint
  backend/sql/getReview.sql
  backend/src/controllers/reviewController.ts
  backend/src/index.ts
  backend/src/models/reviewModel.ts
  backend/src/routes/reviewRoutes.ts
  shared-types/index.ts
  shared-types/reviewTypes.ts
Labels: review-needed

#112 Add review functionality
  backend/src/controllers/reviewController.ts
  backend/src/models/reviewModel.ts
  backend/src/routes/reviewRoutes.ts
  shared-types/reviewTypes.ts
Labels: review-needed

#113 Add saved_at attribute to SavedRecipe
  backend/sql/init.sql
Labels: review-needed

#137 feat: added the recipe modal
  backend/src/models/recipeModel.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/recipeModal.tsx
  frontend/src/components/ui/dialog.tsx
  frontend/src/components/ui/label.tsx
  frontend/src/components/ui/textarea.tsx
Labels: frontend

#139 Change type of display_name from TEXT to VARCHAR
  backend/sql/init.sql
Labels: backend

#158 feat: SQL query to get account saved recipes
  backend/sql/getAccountSavedRecipes.sql
Labels: backend

#154 feat: use tsx watch for hot reload
  backend/package.json
Labels: backend

#152 feat: CHECK constraint to prevent self-following.
  backend/sql/init.sql
Labels: backend

#156 feat: SQL query to unfollow
  backend/sql/deleteAccountFollowing.sql
Labels: backend

#153 feat: unique constraint on follower_id and followee_id to prevent duplicate relationships
  backend/sql/init.sql
Labels: backend
